//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 12:19:20 AM CEST 
//


package services.app.adservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;
import org.w3._2001.xmlschema.Adapter2;
import org.w3._2001.xmlschema.Adapter6;


/**
 * <p>Java class for CarSync complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarSync"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="carManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="carModel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gearboxType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fuelType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="carType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mileage" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="childrenSeatNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="distanceLimitFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="distanceLimit" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="cdw" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="androidFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarSync", propOrder = {
    "year",
    "carManufacturer",
    "carModel",
    "gearboxType",
    "fuelType",
    "carType",
    "mileage",
    "childrenSeatNum",
    "distanceLimitFlag",
    "distanceLimit",
    "cdw",
    "androidFlag",
    "token"
})
public class CarSync {

    @XmlElement(required = true)
    protected String year;
    @XmlElement(required = true)
    protected String carManufacturer;
    @XmlElement(required = true)
    protected String carModel;
    @XmlElement(required = true)
    protected String gearboxType;
    @XmlElement(required = true)
    protected String fuelType;
    @XmlElement(required = true)
    protected String carType;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float mileage;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter6 .class)
    @XmlSchemaType(name = "int")
    protected Integer childrenSeatNum;
    @XmlElement(required = true)
    protected String distanceLimitFlag;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float distanceLimit;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "boolean")
    protected Boolean cdw;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "boolean")
    protected Boolean androidFlag;
    @XmlElement(required = true)
    protected String token;

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the carManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarManufacturer() {
        return carManufacturer;
    }

    /**
     * Sets the value of the carManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarManufacturer(String value) {
        this.carManufacturer = value;
    }

    /**
     * Gets the value of the carModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * Sets the value of the carModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarModel(String value) {
        this.carModel = value;
    }

    /**
     * Gets the value of the gearboxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGearboxType() {
        return gearboxType;
    }

    /**
     * Sets the value of the gearboxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGearboxType(String value) {
        this.gearboxType = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelType(String value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the carType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarType() {
        return carType;
    }

    /**
     * Sets the value of the carType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarType(String value) {
        this.carType = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMileage(Float value) {
        this.mileage = value;
    }

    /**
     * Gets the value of the childrenSeatNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getChildrenSeatNum() {
        return childrenSeatNum;
    }

    /**
     * Sets the value of the childrenSeatNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildrenSeatNum(Integer value) {
        this.childrenSeatNum = value;
    }

    /**
     * Gets the value of the distanceLimitFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistanceLimitFlag() {
        return distanceLimitFlag;
    }

    /**
     * Sets the value of the distanceLimitFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistanceLimitFlag(String value) {
        this.distanceLimitFlag = value;
    }

    /**
     * Gets the value of the distanceLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getDistanceLimit() {
        return distanceLimit;
    }

    /**
     * Sets the value of the distanceLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistanceLimit(Float value) {
        this.distanceLimit = value;
    }

    /**
     * Gets the value of the cdw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Boolean isCdw() {
        return cdw;
    }

    /**
     * Sets the value of the cdw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdw(Boolean value) {
        this.cdw = value;
    }

    /**
     * Gets the value of the androidFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Boolean isAndroidFlag() {
        return androidFlag;
    }

    /**
     * Sets the value of the androidFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndroidFlag(Boolean value) {
        this.androidFlag = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

}
