//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 03:39:42 PM CEST 
//


package services.app.messageservice.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.w3._2001.xmlschema.Adapter5;
import services.app.messageservice.common.db.DbColumnConstants;
import services.app.messageservice.common.db.DbTableConstants;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Conversation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Conversation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="participantPublisherUser" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="participantEndUser" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="adRequest" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Message" type="{http://www.app.services/messageservice/model}Message" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Entity
@Table(name = DbTableConstants.CONVERSATION)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Conversation", propOrder = {
        "id",
        "participantPublisherUser",
        "participantEndUser",
        "adRequest",
        "message"
})
public class Conversation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long id;

    @Column(name = DbColumnConstants.PARTICIPANTPUBLISHERUSER, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long participantPublisherUser;

    @Column(name = DbColumnConstants.PARTICIPANTENDUSER, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long participantEndUser;

    @Column(name = DbColumnConstants.ADREQEUST, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long adRequest;

    @JsonIgnore
    @OneToMany(fetch = FetchType.EAGER)
    @JoinTable(name = DbTableConstants.CONVMSG,
            joinColumns = @JoinColumn(name = "conv_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "msg_id", referencedColumnName = "id"))
    @XmlElement(name = "Message")
    protected List<Message> message;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the participantPublisherUser property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getParticipantPublisherUser() {
        return participantPublisherUser;
    }

    /**
     * Sets the value of the participantPublisherUser property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParticipantPublisherUser(Long value) {
        this.participantPublisherUser = value;
    }

    /**
     * Gets the value of the participantEndUser property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getParticipantEndUser() {
        return participantEndUser;
    }

    /**
     * Sets the value of the participantEndUser property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setParticipantEndUser(Long value) {
        this.participantEndUser = value;
    }

    /**
     * Gets the value of the adRequest property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getAdRequest() {
        return adRequest;
    }

    /**
     * Sets the value of the adRequest property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdRequest(Long value) {
        this.adRequest = value;
    }

    /**
     * Gets the value of the message property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

}
