//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.09 at 10:25:29 PM CEST 
//


package services.app.messageservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;
import org.w3._2001.xmlschema.Adapter4;
import org.w3._2001.xmlschema.Adapter5;
import services.app.messageservice.common.db.DbColumnConstants;
import services.app.messageservice.common.db.DbTableConstants;
import services.app.messageservice.converter.DateAPI;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Message complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Message"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="sendDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="senderFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senderLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="senderEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="recieverSeen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="conversationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Entity
@Table(name = DbTableConstants.MESSAGE)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
        "id",
        "sendDate",
        "content",
        "senderId",
        "senderFirstName",
        "senderLastName",
        "senderEmail",
        "recieverSeen",
        "conversationId"
})
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long id;

    @Temporal(TemporalType.DATE)
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime", parameters = {
            @org.hibernate.annotations.Parameter(name = "databaseZone", value = "UTC"),
            @org.hibernate.annotations.Parameter(name = "javaZone", value = "UTC")
    })
    @Column(name = DbColumnConstants.SENDDATE, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter4.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime sendDate;

    @Column(name = DbColumnConstants.CONTENT, nullable = false)
    @XmlElement(required = true)
    protected String content;

    @Column(name = DbColumnConstants.SENDERID, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long senderId;

    @Column(name = DbColumnConstants.SENDERFIRSTNAME, nullable = false)
    @XmlElement(required = true)
    protected String senderFirstName;

    @Column(name = DbColumnConstants.SENDERLASTNAME, nullable = false)
    @XmlElement(required = true)
    protected String senderLastName;

    @Column(name = DbColumnConstants.SENDEREMAIL, nullable = false)
    @XmlElement(required = true)
    protected String senderEmail;

    @Column(name = DbColumnConstants.RECIEVERSEEN, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "boolean")
    protected Boolean recieverSeen;

    @Column(name = DbColumnConstants.CONVERSATIONID, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long conversationId;

    @JsonProperty("sendDate")
    public String getTheSendDate() {
        return DateAPI.DateTimeToStringDateTime(sendDate);
    }

    @JsonProperty("sendDate")
    public void getTheSendDate(String sendDate) {
        this.sendDate = DateAPI.DateTimeStringToDateTime(sendDate);
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the sendDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public DateTime getSendDate() {
        return sendDate;
    }

    /**
     * Sets the value of the sendDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSendDate(DateTime value) {
        this.sendDate = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the senderId property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * Sets the value of the senderId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderId(Long value) {
        this.senderId = value;
    }

    /**
     * Gets the value of the senderFirstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderFirstName() {
        return senderFirstName;
    }

    /**
     * Sets the value of the senderFirstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderFirstName(String value) {
        this.senderFirstName = value;
    }

    /**
     * Gets the value of the senderLastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderLastName() {
        return senderLastName;
    }

    /**
     * Sets the value of the senderLastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderLastName(String value) {
        this.senderLastName = value;
    }

    /**
     * Gets the value of the senderEmail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the recieverSeen property.
     *
     * @return possible object is
     * {@link String }
     */
    public Boolean isRecieverSeen() {
        return recieverSeen;
    }

    /**
     * Sets the value of the recieverSeen property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecieverSeen(Boolean value) {
        this.recieverSeen = value;
    }

    /**
     * Gets the value of the conversationId property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getConversationId() {
        return conversationId;
    }

    /**
     * Sets the value of the conversationId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConversationId(Long value) {
        this.conversationId = value;
    }

}
