//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 06:14:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.app.services/carrequestservice/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package services.app.carrequestservice.model;
