//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:27:13 AM CEST 
//


package services.app.carrequestservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;
import org.w3._2001.xmlschema.Adapter4;
import org.w3._2001.xmlschema.Adapter5;
import services.app.carrequestservice.common.db.DbColumnConstants;
import services.app.carrequestservice.common.db.DbTableConstants;
import services.app.carrequestservice.converter.DateAPI;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Request complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="status" type="{http://www.app.services/carrequestservice/model}RequestStatusEnum"/&gt;
 *         &lt;element name="submitDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="endUserId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="endUserFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUserLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endUserEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bundle" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="publisherUserId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="publisherUserFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="publisherUserLastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="publisherUserEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ads" type="{http://www.app.services/carrequestservice/model}Ad" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@Builder
@Entity
@Table(name = DbTableConstants.REQUEST)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", propOrder = {
        "id",
        "status",
        "submitDate",
        "endUserId",
        "endUserFirstName",
        "endUserLastName",
        "endUserEmail",
        "bundle",
        "publisherUserId",
        "publisherUserFirstName",
        "publisherUserLastName",
        "publisherUserEmail",
        "ads"
})
public class Request {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long id;

    @Enumerated(EnumType.STRING)
    @Column(name = DbColumnConstants.STATUS, nullable = false)
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RequestStatusEnum status;

    @Temporal(TemporalType.DATE)
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime", parameters = {
            @org.hibernate.annotations.Parameter(name = "databaseZone", value = "UTC"),
            @org.hibernate.annotations.Parameter(name = "javaZone", value = "UTC")
    })
    @Column(name = DbColumnConstants.SUBMITDATE, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter4.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime submitDate;

    @Column(name = DbColumnConstants.ENDUSERID, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long endUserId;

    @Column(name = DbColumnConstants.ENDUSERFIRSTNAME, nullable = false)
    @XmlElement(required = true)
    protected String endUserFirstName;

    @Column(name = DbColumnConstants.ENDUSERLASTNAME, nullable = false)
    @XmlElement(required = true)
    protected String endUserLastName;

    @Column(name = DbColumnConstants.ENDUSEREMAIL, nullable = false)
    @XmlElement(required = true)
    protected String endUserEmail;

    @Column(name = DbColumnConstants.BUNDLE, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "boolean")
    protected Boolean bundle;

    @Column(name = DbColumnConstants.PUBLISHERUSERID, nullable = false)
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long publisherUserId;

    @Column(name = DbColumnConstants.PUBLISHERUSERFIRSTNAME, nullable = false)
    @XmlElement(required = true)
    protected String publisherUserFirstName;

    @Column(name = DbColumnConstants.PUBLISHERUSERLASTNAME, nullable = false)
    @XmlElement(required = true)
    protected String publisherUserLastName;

    @Column(name = DbColumnConstants.PUBLISHERUSEREMAIL, nullable = false)
    @XmlElement(required = true)
    protected String publisherUserEmail;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = DbTableConstants.REQUESTAD,
            joinColumns = @JoinColumn(name = "ad_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(name = "request_id", referencedColumnName = "id"))
    @XmlElement(required = true)
    protected List<Ad> ads;

    @JsonProperty("submitDate")
    public String getTheSubmitDate() {
        return DateAPI.DateTimeToStringDateTime(submitDate);
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link RequestStatusEnum }
     */
    public RequestStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link RequestStatusEnum }
     */
    public void setStatus(RequestStatusEnum value) {
        this.status = value;
    }

    /**
     * Gets the value of the submitDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public DateTime getSubmitDate() {
        return submitDate;
    }

    /**
     * Sets the value of the submitDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubmitDate(DateTime value) {
        this.submitDate = value;
    }

    /**
     * Gets the value of the endUserId property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getEndUserId() {
        return endUserId;
    }

    /**
     * Sets the value of the endUserId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndUserId(Long value) {
        this.endUserId = value;
    }

    /**
     * Gets the value of the endUserFirstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndUserFirstName() {
        return endUserFirstName;
    }

    /**
     * Sets the value of the endUserFirstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndUserFirstName(String value) {
        this.endUserFirstName = value;
    }

    /**
     * Gets the value of the endUserLastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndUserLastName() {
        return endUserLastName;
    }

    /**
     * Sets the value of the endUserLastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndUserLastName(String value) {
        this.endUserLastName = value;
    }

    /**
     * Gets the value of the endUserEmail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEndUserEmail() {
        return endUserEmail;
    }

    /**
     * Sets the value of the endUserEmail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndUserEmail(String value) {
        this.endUserEmail = value;
    }

    /**
     * Gets the value of the bundle property.
     *
     * @return possible object is
     * {@link String }
     */
    public Boolean isBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBundle(Boolean value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the publisherUserId property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getPublisherUserId() {
        return publisherUserId;
    }

    /**
     * Sets the value of the publisherUserId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUserId(Long value) {
        this.publisherUserId = value;
    }

    /**
     * Gets the value of the publisherUserFirstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPublisherUserFirstName() {
        return publisherUserFirstName;
    }

    /**
     * Sets the value of the publisherUserFirstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUserFirstName(String value) {
        this.publisherUserFirstName = value;
    }

    /**
     * Gets the value of the publisherUserLastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPublisherUserLastName() {
        return publisherUserLastName;
    }

    /**
     * Sets the value of the publisherUserLastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUserLastName(String value) {
        this.publisherUserLastName = value;
    }

    /**
     * Gets the value of the publisherUserEmail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPublisherUserEmail() {
        return publisherUserEmail;
    }

    /**
     * Sets the value of the publisherUserEmail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUserEmail(String value) {
        this.publisherUserEmail = value;
    }

    /**
     * Gets the value of the ads property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ads property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ad }
     */
    public List<Ad> getAds() {
        if (ads == null) {
            ads = new ArrayList<Ad>();
        }
        return this.ads;
    }

}
