//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.05 at 12:02:15 AM CEST 
//


package services.app.carrequestservice.model;

import agent.app.converter.DateAPI;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;
import org.w3._2001.xmlschema.Adapter1;
import org.w3._2001.xmlschema.Adapter4;
import org.w3._2001.xmlschema.Adapter5;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Request complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Request"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="status" type="{http://www.app.services/carrequestservice/model}RequestStatusEnum"/&gt;
 *         &lt;element name="submitDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="endUser" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="publisherUser" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="bundle" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ads" type="{http://www.app.services/carrequestservice/model}Ad" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", propOrder = {
        "id",
        "status",
        "submitDate",
        "endUser",
        "publisherUser",
        "bundle",
        "ads"
})
public class Request {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RequestStatusEnum status;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter4.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime submitDate;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long endUser;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter5.class)
    @XmlSchemaType(name = "long")
    protected Long publisherUser;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "boolean")
    protected Boolean bundle;
    @XmlElement(required = true)
    protected List<Ad> ads;

    @JsonProperty("submitDate")
    public String getTheSubmitDate() {
        return DateAPI.DateTimeToStringDateTime(submitDate);
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link RequestStatusEnum }
     */
    public RequestStatusEnum getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link RequestStatusEnum }
     */
    public void setStatus(RequestStatusEnum value) {
        this.status = value;
    }

    /**
     * Gets the value of the submitDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public DateTime getSubmitDate() {
        return submitDate;
    }

    /**
     * Sets the value of the submitDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubmitDate(DateTime value) {
        this.submitDate = value;
    }

    /**
     * Gets the value of the endUser property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getEndUser() {
        return endUser;
    }

    /**
     * Sets the value of the endUser property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEndUser(Long value) {
        this.endUser = value;
    }

    /**
     * Gets the value of the publisherUser property.
     *
     * @return possible object is
     * {@link String }
     */
    public Long getPublisherUser() {
        return publisherUser;
    }

    /**
     * Sets the value of the publisherUser property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUser(Long value) {
        this.publisherUser = value;
    }

    /**
     * Gets the value of the bundle property.
     *
     * @return possible object is
     * {@link String }
     */
    public Boolean isBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBundle(Boolean value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the ads property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ads property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ad }
     */
    public List<Ad> getAds() {
        if (ads == null) {
            ads = new ArrayList<Ad>();
        }
        return this.ads;
    }

}
