//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:37:58 AM CEST 
//


package services.app.carrequestservice.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="publisherUserEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="report" type="{http://www.app.services/carrequestservice/model}Report"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "publisherUserEmail",
        "identifier",
        "requestId",
        "report"
})
@XmlRootElement(name = "submitReportRequest")
public class SubmitReportRequest {

    @XmlElement(required = true)
    protected String publisherUserEmail;
    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected Long requestId;
    @XmlElement(required = true)
    protected Report report;

    public Long getRequestId() {
        return requestId;
    }


    public void setRequestId(Long value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the publisherUserEmail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPublisherUserEmail() {
        return publisherUserEmail;
    }

    /**
     * Sets the value of the publisherUserEmail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublisherUserEmail(String value) {
        this.publisherUserEmail = value;
    }

    /**
     * Gets the value of the identifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the report property.
     *
     * @return possible object is
     * {@link Report }
     */
    public Report getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     *
     * @param value allowed object is
     *              {@link Report }
     */
    public void setReport(Report value) {
        this.report = value;
    }

}
