//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 03:30:49 PM CEST 
//


package services.app.pricelistanddiscountservice.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.app.pricelistanddiscountservice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.app.pricelistanddiscountservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddPriceListRequest }
     * 
     */
    public AddPriceListRequest createAddPriceListRequest() {
        return new AddPriceListRequest();
    }

    /**
     * Create an instance of {@link AddPriceListResponse }
     * 
     */
    public AddPriceListResponse createAddPriceListResponse() {
        return new AddPriceListResponse();
    }

    /**
     * Create an instance of {@link EditPriceListRequest }
     * 
     */
    public EditPriceListRequest createEditPriceListRequest() {
        return new EditPriceListRequest();
    }

    /**
     * Create an instance of {@link EditPriceListResponse }
     * 
     */
    public EditPriceListResponse createEditPriceListResponse() {
        return new EditPriceListResponse();
    }

    /**
     * Create an instance of {@link DeletePriceListRequest }
     * 
     */
    public DeletePriceListRequest createDeletePriceListRequest() {
        return new DeletePriceListRequest();
    }

    /**
     * Create an instance of {@link DeletePriceListResponse }
     * 
     */
    public DeletePriceListResponse createDeletePriceListResponse() {
        return new DeletePriceListResponse();
    }

    /**
     * Create an instance of {@link AddDiscountListRequest }
     * 
     */
    public AddDiscountListRequest createAddDiscountListRequest() {
        return new AddDiscountListRequest();
    }

    /**
     * Create an instance of {@link AddDiscountListResponse }
     * 
     */
    public AddDiscountListResponse createAddDiscountListResponse() {
        return new AddDiscountListResponse();
    }

    /**
     * Create an instance of {@link EditDiscountListRequest }
     * 
     */
    public EditDiscountListRequest createEditDiscountListRequest() {
        return new EditDiscountListRequest();
    }

    /**
     * Create an instance of {@link EditDiscountListResponse }
     * 
     */
    public EditDiscountListResponse createEditDiscountListResponse() {
        return new EditDiscountListResponse();
    }

    /**
     * Create an instance of {@link DeleteDiscountListRequest }
     * 
     */
    public DeleteDiscountListRequest createDeleteDiscountListRequest() {
        return new DeleteDiscountListRequest();
    }

    /**
     * Create an instance of {@link DeleteDiscountListResponse }
     * 
     */
    public DeleteDiscountListResponse createDeleteDiscountListResponse() {
        return new DeleteDiscountListResponse();
    }

    /**
     * Create an instance of {@link AddDiscountListToAdRequest }
     * 
     */
    public AddDiscountListToAdRequest createAddDiscountListToAdRequest() {
        return new AddDiscountListToAdRequest();
    }

    /**
     * Create an instance of {@link AddDiscountListToAdResponse }
     * 
     */
    public AddDiscountListToAdResponse createAddDiscountListToAdResponse() {
        return new AddDiscountListToAdResponse();
    }

    /**
     * Create an instance of {@link RemoveDiscountListFromAdRequest }
     * 
     */
    public RemoveDiscountListFromAdRequest createRemoveDiscountListFromAdRequest() {
        return new RemoveDiscountListFromAdRequest();
    }

    /**
     * Create an instance of {@link RemoveDiscountListFromAdResponse }
     * 
     */
    public RemoveDiscountListFromAdResponse createRemoveDiscountListFromAdResponse() {
        return new RemoveDiscountListFromAdResponse();
    }

    /**
     * Create an instance of {@link PriceList }
     * 
     */
    public PriceList createPriceList() {
        return new PriceList();
    }

    /**
     * Create an instance of {@link DiscountList }
     * 
     */
    public DiscountList createDiscountList() {
        return new DiscountList();
    }

}
