package agent.app.common.db;

public class DbColumnConstants {
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String FIRSTNAME = "firstName";
    public static final String LASTNAME = "lastName";
    public static final String NAME = "name";
    public static final String LASTPASSWORDRESETDATE = "lastPasswordResetDate";
    public static final String LOCATION = "location";
    public static final String DISTANCELIMITFLAG = "distanceLimitFlag";
    public static final String DISTANCELIMIT = "distanceLimit";
    public static final String PUBLISHDATE = "publishDate";
    public static final String RATINGNUM = "ratingNum";
    public static final String RATINGCOUNT = "ratingCount";
    public static final String DELETED = "deleted";
    public static final String ENABLED = "enabled";
    public static final String RENTCNT = "rentCnt";
    public static final String STARTDATE = "startDate";
    public static final String ENDDATE = "endDate";
    public static final String CREATIONDATE = "creationDate";
    public static final String PRICEPERKM = "pricePerKm";
    public static final String PRICEPERCWD = "pricePerCwd";
    public static final String PRICEPERDAY = "pricePerDay";
    public static final String DISCOUNT = "discount";
    public static final String STATUS = "status";
    public static final String SUBMITDATE = "submitDate";
    public static final String BUNDLE = "bundle";
    public static final String CONTENT = "content";
    public static final String APPROVED = "approved";
    public static final String YEAR = "year";
    public static final String CARMANUFACTURER = "carManufacturer";
    public static final String CARMODEL = "carModel";
    public static final String GEARBOXTYPE = "gearboxType";
    public static final String FUELTYPE = "fuelType";
    public static final String CARTYPE = "carType";
    public static final String MILEAGE = "mileage";
    public static final String CHILDRENSEATNUM = "childrenSeatNum";
    public static final String CDW = "cdw";
    public static final String ANDROIDFLAG = "androidFlag";
    public static final String TOKEN = "token";
    public static final String ADDRESS = "address";
    public static final String PMB = "pmb";
    public static final String FIRMNAME = "firmName";
    public static final String DESCRIPTION = "description";
    public static final String DISTANCETRAVELED = "distanceTraveled";
    public static final String ADLIMITNUM = "adLimitNum";
    public static final String OBLIGED = "obliged";
    public static final String CANCELEDCNT = "canceledCnt";
    public static final String SENDDATE = "sendDate";
    public static final String COVERPHOTO = "coverPhoto";

}
